name: Development build

on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop/*
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.ref_name }}
  GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4g -XX:MaxMetaspaceSize=512m'"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Need the tags to build
      - name: Setup
        uses: damontecres/wholphin/.github/actions/setup@main

      - name: Load media3 module cache
        id: cache_media3_module
        uses: actions/cache/restore@v5
        with:
          path: |
            wholphin-media3/libs
          key: ${{ runner.os }}-media3-${{ hashFiles('**/libs.versions.toml', '**/wholphin-media3/build_decoders.sh') }}
      - name: Load libmpv module cache
        id: cache_libmpv_module
        # if: ${{ inputs.cache }}
        uses: actions/cache/restore@v5
        with:
          path: |
            wholphin-mpv/build/libmpv/prefix
          key: ${{ runner.os }}-libmpv-${{ hashFiles('**/wholphin-mpv/src/native/**/*.sh', '**/wholphin-mpv/.github/workflows/*.yml') }}

      - name: Install dependencies
        if: steps.cache_media3_module.outputs.cache-hit != 'true' || steps.cache_libmpv_module.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema jinja2
          sudo apt update
          sudo apt install -y build-essential autoconf pkg-config libtool ninja-build unzip wget meson nasm gettext

      # media3
      - name: Build media3 decoders
        id: media3-decoder
        if: steps.cache_media3_module.outputs.cache-hit != 'true'
        shell: bash
        run: |
          ./wholphin-media3/build_decoders.sh "${{ env.ANDROID_SDK_ROOT }}/ndk/${{ env.NDK_VERSION }}"
      - name: Publish media3 decoder
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          ./wholphin-media3/publish.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save media3 module cache
        id: cache_media3_module_save
        uses: actions/cache/save@v5
        with:
          path: |
            wholphin-media3/libs
          key: ${{ steps.cache_media3_module.outputs.cache-primary-key }}

      # MPV
      - name: Get libmpv dependencies
        if: steps.cache_libmpv_module.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd wholphin-mpv/src/native
          ./get_dependencies.sh
      - name: Build libmpv
        if: steps.cache_libmpv_module.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cd wholphin-mpv/src/native
          ./buildall.sh --clean --arch arm64 mpv
          ./buildall.sh --arch armv7l mpv
          ./buildall.sh --arch x86_64 mpv

      - name: Build aar
        shell: bash
        run: |
          ./gradlew assembleRelease assembleDebug
      - name: Publish aar
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload aar
        uses: actions/upload-artifact@v7
        with:
          name: wholphin-mpv-aar
          path: |
            wholphin-media3/libs/*.aar
            wholphin-mpv/build/outputs/aar/*.aar
          compression-level: 0
      - name: Save libmpv module cache
        id: cache_libmpv_module_save
        uses: actions/cache/save@v5
        with:
          path: |
            wholphin-mpv/build/libmpv/prefix
          key: ${{ steps.cache_libmpv_module.outputs.cache-primary-key }}
